### ISSUE TITLE
change on quickstart

### ISSUE THREAD

**Issue by izelpii** [orchest/quickstart#1]
Hello,

I think you need to change the quickstart file explore-data.ipynb ... on the second cell:
From: 
df_data, df_target = data["data"]
To:
df_data, df_target = data["training_data"]

Otherwise it doesn't work. Right?

**Comment by ricklamers** [comment]
Thanks for bringing this up!

@izelpii https://github.com/orchest/quickstart/blob/main/get-data.py outputs with the name `"data"` so it should be correct. What makes you think it should be `"training_data"`? I could very well be missing something.

**Comment by izelpii** [comment]
Now that I saw the code, it should be data - but the previous step - get-data.py should change to data as well. Currently that file has 'traning_data' --> and this causes the explore-data step to fail running.

**Comment by ricklamers** [comment]
@izelpii get-data.py (https://github.com/orchest/quickstart/blob/main/get-data.py) on the main branch seems to have the correct `orchest.output((df_data, df_target), name="data")` name value on line 19. Perhaps you have an older version checked out?

**Comment by izelpii** [comment]
You are right. The web version on the tutorial needs to be changed here:

https://orchest.readthedocs.io/en/stable/getting_started/quickstart.html

**Comment by ricklamers** [comment]
Ah now I see! It was wrong in the docs. Thanks for spotting this.

https://github.com/orchest/orchest/blob/master/docs/source/getting_started/quickstart.rst (Should be fixed, stable docs will update on the next release - latest version of the docs will update shortly).
